### ISSUE TITLE
Unable to poetry install

### ISSUE THREAD

**Issue by sb10** [wtsi-hgi/softpack-core#12]
* SoftPack Core version: feature/mutations branch
* Python version: 3.11.0
* Operating System: linux

### Description

Do a poetry install to start developing the code.

### What I Did

```
cd ~/src/python/softpack
git clone [git@github.com](mailto:git@github.com):wtsi-hgi/softpack-core.git
cd ~/src/python/softpack/softpack-core
git checkout feature/mutations

module load ISG/python/3.11.0
python -m venv .venv
source .venv/bin/activate
pip install --upgrade pip

pip install poetry
poetry install --with dev,doc,test
```

The last command results in:
```
Traceback (most recent call last):
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/cleo/application.py", line 327, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/console/application.py", line 188, in _run
    self._load_plugins(io)
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/console/application.py", line 354, in _load_plugins
    manager.load_plugins()
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/plugins/plugin_manager.py", line 38, in load_plugins
    self._load_plugin_entry_point(ep)
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/plugins/plugin_manager.py", line 76, in _load_plugin_entry_point
    plugin = ep.load()  # type: ignore[no-untyped-call]
             ^^^^^^^^^
  File "/software/python-3.11.0/lib/python3.11/importlib/metadata/__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/python-3.11.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry_plugin_export/plugins.py", line 7, in <module>
    from poetry_plugin_export.command import ExportCommand
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry_plugin_export/command.py", line 10, in <module>
    from poetry_plugin_export.exporter import Exporter
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry_plugin_export/exporter.py", line 11, in <module>
    from poetry.repositories.http_repository import HTTPRepository
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/repositories/http_repository.py", line 13, in <module>
    import requests
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
ModuleNotFoundError: No module named 'charset_normalizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/console/application.py", line 405, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/cleo/application.py", line 338, in run
    self.render_error(e, io)
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/console/application.py", line 394, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (  # noqa: E501
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/mixology/solutions/providers/__init__.py", line 3, in <module>
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/mixology/solutions/providers/python_requirement_solution_provider.py", line 9, in <module>
    from poetry.puzzle.exceptions import SolverProblemError
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/puzzle/__init__.py", line 3, in <module>
    from poetry.puzzle.solver import Solver
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/puzzle/solver.py", line 16, in <module>
    from poetry.puzzle.provider import Indicator
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/puzzle/provider.py", line 25, in <module>
    from poetry.packages.direct_origin import DirectOrigin
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/packages/direct_origin.py", line 14, in <module>
    from poetry.vcs.git import Git
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/vcs/git/__init__.py", line 3, in <module>
    from poetry.vcs.git.backend import Git
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/vcs/git/backend.py", line 22, in <module>
    from poetry.utils.authenticator import get_default_authenticator
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/poetry/utils/authenticator.py", line 16, in <module>
    import requests
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv/lib/python3.11/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
ModuleNotFoundError: No module named 'charset_normalizer'
```

**Comment by sb10** [comment]
This was solved by doing:

```
pip install chardet
[...]
Successfully installed chardet-5.2.0
```

Should chardet be explicitly defined as a dependency in one of the files?

**Comment by sb10** [comment]
The error given in the first message is actually the error you get on attempts after the first one. With a fresh venv, the initial error is:

```
Installing dependencies from lock file

Package operations: 148 installs, 16 updates, 0 removals

  • Downgrading pip (23.2.1 -> 23.1.2)
  • Installing six (1.16.0)
  • Downgrading certifi (2023.7.22 -> 2023.5.7)
  • Downgrading charset-normalizer (3.2.0 -> 3.1.0): Failed

  CalledProcessError

  Command '['/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/bin/python', '-m', 'pip', 'uninstall', 'charset-normalizer', '-y']' returned non-zero exit status 2.

  at /software/python-3.11.0/lib/python3.11/subprocess.py:569 in run
       565│             # We don't call process.wait() as .__exit__ does that for us.
       566│             raise
       567│         retcode = process.poll()
       568│         if check and retcode:
    →  569│             raise CalledProcessError(retcode, process.args,
       570│                                      output=stdout, stderr=stderr)
       571│     return CompletedProcess(process.args, retcode, stdout, stderr)
       572│
       573│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/bin/python', '-m', 'pip', 'uninstall', 'charset-normalizer', '-y'] errored with the following return code 2

  Output:
  Found existing installation: charset-normalizer 3.2.0
  Uninstalling charset-normalizer-3.2.0:
    Successfully uninstalled charset-normalizer-3.2.0
  ERROR: Exception:
  Traceback (most recent call last):
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
      status = run_func(*args)
               ^^^^^^^^^^^^^^^
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_internal/commands/uninstall.py", line 110, in run
      uninstall_pathset.commit()
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_internal/req/req_uninstall.py", line 432, in commit
      self._moved_paths.commit()
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_internal/req/req_uninstall.py", line 278, in commit
      save_dir.cleanup()
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_internal/utils/temp_dir.py", line 173, in cleanup
      rmtree(self._path)
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_vendor/tenacity/__init__.py", line 291, in wrapped_f
      return self(f, *args, **kw)
             ^^^^^^^^^^^^^^^^^^^^
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_vendor/tenacity/__init__.py", line 381, in __call__
      do = self.iter(retry_state=retry_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_vendor/tenacity/__init__.py", line 327, in iter
      raise retry_exc.reraise()
            ^^^^^^^^^^^^^^^^^^^
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_vendor/tenacity/__init__.py", line 160, in reraise
      raise self.last_attempt.result()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/software/python-3.11.0/lib/python3.11/concurrent/futures/_base.py", line 449, in result
      return self.__get_result()
             ^^^^^^^^^^^^^^^^^^^
    File "/software/python-3.11.0/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
      raise self._exception
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_vendor/tenacity/__init__.py", line 384, in __call__
      result = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
    File "/nfs/users/nfs_s/sb10/src/python/softpack/softpack-core/.venv_fresh/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 130, in rmtree
      shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
    File "/software/python-3.11.0/lib/python3.11/shutil.py", line 731, in rmtree
      _rmtree_safe_fd(fd, path, onerror)
    File "/software/python-3.11.0/lib/python3.11/shutil.py", line 682, in _rmtree_safe_fd
      onerror(os.unlink, fullname, sys.exc_info())
    File "/software/python-3.11.0/lib/python3.11/shutil.py", line 680, in _rmtree_safe_fd
      os.unlink(entry.name, dir_fd=topfd)
  OSError: [Errno 16] Device or resource busy: '.nfs0000000131b7699f000071d6'


  at .venv_fresh/lib/python3.11/site-packages/poetry/utils/env/base_env.py:363 in _run
      359│                 output = subprocess.check_output(
      360│                     cmd, stderr=stderr, env=env, text=True, **kwargs
      361│                 )
      362│         except CalledProcessError as e:
    → 363│             raise EnvCommandError(e, input=input_)
      364│
      365│         return output
      366│
      367│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

  • Installing markupsafe (2.1.2)
  • Installing pyasn1 (0.5.0)
  • Installing python-dateutil (2.8.2)
  • Installing pyyaml (6.0)
  • Installing sniffio (1.3.0)
  • Downgrading urllib3 (2.0.4 -> 1.26.15)
```

So it's an nfs issue, but one that's consistent: it's happened on 3 fresh install attempts in a row.

Once the downgrade of charset-normalizer "fails" (even though it says the uninstall worked), it can no longer install a new one for some reason, perhaps incomplete requirements specified up the line.

Anyway, is there any harm in having an explicit chardet dependency?

Having done the poetry install, tests won't run without doing:

```
git clone -c feature.manyFiles=true --depth 1 https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
```

This should be added to the README.md
